apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      d: dev
  template:
    metadata:
      labels:
        d: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: pv-volume
          mountPath: /app
      volumes:
      - name: pv-volume
        persistentVolumeClaim:
          claimName: task-pv-claim
        
