apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
       d: dev
  template:
    metadata:
      labels:
        d: dev
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-one

      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: secret-volume
          mountPath: /mani
        ports:  
        - containerPort: 80   
              
